
version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: backend/
    networks:
      - proxynet
    ports: 
      - 5002:8080
  redis:
    image: redis
    networks: 
      - proxynet
    
